### ISSUE TITLE
Max width for texts.

### ISSUE THREAD

**Issue by E-fais** [sreejit112/sreejit112.github.io#1]
Long texts with full width are not looling good. You can use a max-width for texts and align texts in center. It will look much better , i believe

**Comment by Sreejit-Sengupto** [comment]
Okay🙌 Thanks for suggesting! I will fix it ASAP🪛

**Comment by E-fais** [comment]
![Marvel Arena - Google Chrome 31-10-2022 6 25 54 PM](https://user-images.githubusercontent.com/102040088/199045597-1678c48c-ff41-41dd-9832-17869d759649.png)
have a look :)

**Comment by Sreejit-Sengupto** [comment]
Actually I want it to remain in cards, like it was before, one section in white and one in black!🤔

**Comment by E-fais** [comment]
Okay let it be , but it is always good to avoid full width texts, It is a common practice to make it little bit shorter in width. It is totally up to you. Just  a suggestion :)

**Comment by Sreejit-Sengupto** [comment]
> Okay let it be , but it is always good to avoid full width texts, It is a common practice to make it little bit shorter in width. It is totally up to you. Just a suggestion :)

I will shorten the width of the text! Thanks for suggesting ☺️
